#############################################################################
# Makefile for building: commhistory-daemon
# Generated by qmake (2.01a) (Qt 4.8.3) on: Tue Oct 8 11:06:27 2013
# Project:  commhistory-daemon.pro
# Template: subdirs
# Command: /usr/lib/qt4/bin/qmake -o Makefile commhistory-daemon.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-data \
		sub-tests \
		sub-translations

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/src/src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/src/src.pro -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
data/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) data/ || $(MKDIR) data/ 
	cd data/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/data/data.pro -o $(MAKEFILE)
sub-data-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) data/ || $(MKDIR) data/ 
	cd data/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/data/data.pro -o $(MAKEFILE)
sub-data: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE)
sub-data-make_default-ordered: data/$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) 
sub-data-make_default: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) 
sub-data-make_first-ordered: data/$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) first
sub-data-make_first: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) first
sub-data-all-ordered: data/$(MAKEFILE) sub-src-all-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) all
sub-data-all: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) all
sub-data-clean-ordered: data/$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) clean
sub-data-clean: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) clean
sub-data-distclean-ordered: data/$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) distclean
sub-data-distclean: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) distclean
sub-data-install_subtargets-ordered: data/$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) install
sub-data-install_subtargets: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) install
sub-data-uninstall_subtargets-ordered: data/$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-data-uninstall_subtargets: data/$(MAKEFILE) FORCE
	cd data/ && $(MAKE) -f $(MAKEFILE) uninstall
tests/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/tests/tests.pro -o $(MAKEFILE)
sub-tests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tests/ || $(MKDIR) tests/ 
	cd tests/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/tests/tests.pro -o $(MAKEFILE)
sub-tests: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE)
sub-tests-make_default-ordered: tests/$(MAKEFILE) sub-data-make_default-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_default: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) 
sub-tests-make_first-ordered: tests/$(MAKEFILE) sub-data-make_first-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) first
sub-tests-make_first: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) first
sub-tests-all-ordered: tests/$(MAKEFILE) sub-data-all-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) all
sub-tests-all: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) all
sub-tests-clean-ordered: tests/$(MAKEFILE) sub-data-clean-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-clean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) clean
sub-tests-distclean-ordered: tests/$(MAKEFILE) sub-data-distclean-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-distclean: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tests-install_subtargets-ordered: tests/$(MAKEFILE) sub-data-install_subtargets-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) install
sub-tests-install_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) install
sub-tests-uninstall_subtargets-ordered: tests/$(MAKEFILE) sub-data-uninstall_subtargets-ordered  FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-tests-uninstall_subtargets: tests/$(MAKEFILE) FORCE
	cd tests/ && $(MAKE) -f $(MAKEFILE) uninstall
translations/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) translations/ || $(MKDIR) translations/ 
	cd translations/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/translations/translations.pro -o $(MAKEFILE)
sub-translations-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) translations/ || $(MKDIR) translations/ 
	cd translations/ && $(QMAKE) /home/ramoncin/socam/svn/socam/trunk/apps/commhistory-daemon/translations/translations.pro -o $(MAKEFILE)
sub-translations: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE)
sub-translations-make_default-ordered: translations/$(MAKEFILE) sub-tests-make_default-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) 
sub-translations-make_default: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) 
sub-translations-make_first-ordered: translations/$(MAKEFILE) sub-tests-make_first-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) first
sub-translations-make_first: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) first
sub-translations-all-ordered: translations/$(MAKEFILE) sub-tests-all-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) all
sub-translations-all: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) all
sub-translations-clean-ordered: translations/$(MAKEFILE) sub-tests-clean-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) clean
sub-translations-clean: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) clean
sub-translations-distclean-ordered: translations/$(MAKEFILE) sub-tests-distclean-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) distclean
sub-translations-distclean: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) distclean
sub-translations-install_subtargets-ordered: translations/$(MAKEFILE) sub-tests-install_subtargets-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) install
sub-translations-install_subtargets: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) install
sub-translations-uninstall_subtargets-ordered: translations/$(MAKEFILE) sub-tests-uninstall_subtargets-ordered  FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-translations-uninstall_subtargets: translations/$(MAKEFILE) FORCE
	cd translations/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: commhistory-daemon.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile commhistory-daemon.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile commhistory-daemon.pro

qmake_all: sub-src-qmake_all sub-data-qmake_all sub-tests-qmake_all sub-translations-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-data-make_default-ordered sub-tests-make_default-ordered sub-translations-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-data-make_first-ordered sub-tests-make_first-ordered sub-translations-make_first-ordered FORCE
all: sub-src-all-ordered sub-data-all-ordered sub-tests-all-ordered sub-translations-all-ordered FORCE
clean: sub-src-clean-ordered sub-data-clean-ordered sub-tests-clean-ordered sub-translations-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-data-distclean-ordered sub-tests-distclean-ordered sub-translations-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-data-install_subtargets-ordered sub-tests-install_subtargets-ordered sub-translations-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-data-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered sub-translations-uninstall_subtargets-ordered FORCE

sub-src-check_ordered: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
sub-data-check_ordered: data/$(MAKEFILE) sub-src-check_ordered 
	cd data/ && $(MAKE) -f $(MAKEFILE) check
sub-tests-check_ordered: tests/$(MAKEFILE) sub-data-check_ordered 
	cd tests/ && $(MAKE) -f $(MAKEFILE) check
sub-translations-check_ordered: translations/$(MAKEFILE) sub-tests-check_ordered 
	cd translations/ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-check_ordered sub-data-check_ordered sub-tests-check_ordered sub-translations-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

